In [2]:
import numpy as np

In [3]:
arr_1dimensional= np.arange(10, 51)
print(arr_1dimensional)
arr_3x3 = np.random.rand(3, 3)
print(arr_3x3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.35876386 0.18655858 0.21450632]
 [0.31883554 0.13556586 0.42486606]
 [0.80718903 0.43408672 0.92299422]]


In [4]:
shape_1d, size_1d, dtype_1d = arr_1d.shape, arr_1d.size, arr_1d.dtype
shape_3x3, size_3x3, dtype_3x3 = arr_3x3.shape, arr_3x3.size, arr_3x3.dtype
print("Shape, Size, DataType of 1D:", shape_1d, size_1d, dtype_1d)
print("Shape, Size, DataType of 3x3:", shape_3x3, size_3x3, dtype_3x3)


Shape, Size, DataType of 1D: (41,) 41 int32
Shape, Size, DataType of 3x3: (3, 3) 9 float64


In [5]:
arr_1d_plus_5 = arr_1d + 5
arr_2d_1 = np.random.rand(3, 3)
arr_2d_2 = np.random.rand(3, 3)
arr_2d_mult = arr_2d_1 * arr_2d_2
print("Array +5:", arr_1d_plus_5)
print("Element-wise Multiplication:\n", arr_2d_mult)

Array +5: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Element-wise Multiplication:
 [[0.18244566 0.59783682 0.54300911]
 [0.03408235 0.09736858 0.06981644]
 [0.0700479  0.08533001 0.07666902]]


In [6]:
arr_5x5 = np.arange(1, 26).reshape(5, 5)
first_row = arr_5x5[0, :]
last_column = arr_5x5[:, -1]
subarray = arr_5x5[:3, :2]
print("First row:", first_row)
print("Last column:", last_column)
print("Subarray:\n", subarray)

First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Subarray:
 [[ 1  2]
 [ 6  7]
 [11 12]]


In [7]:
arr_10 = np.random.randint(1, 101, 10)
max_val = np.max(arr_10)
min_val = np.min(arr_10)
mean_val = np.mean(arr_10)
std_dev = np.std(arr_10)
print("Max, Min, Mean, Std:", max_val, min_val, mean_val, std_dev)

Max, Min, Mean, Std: 90 2 40.1 30.99822575567834


In [8]:
arr_1d_to_3x4 = np.arange(1, 13).reshape(3, 4)
print("Reshaped 3x4:\n", arr_1d_to_3x4)

Reshaped 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
arr_ones = np.ones((3, 3))
arr_broadcasted = arr_ones + np.array([1, 2, 3])
print("Broadcasted Matrix:\n", arr_broadcasted)

Broadcasted Matrix:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [10]:
arr_rand = np.random.randint(1, 51, 10)
filtered_arr = arr_rand[arr_rand % 5 == 0]
print("Filtered (Divisible by 5):", filtered_arr)

Filtered (Divisible by 5): [50]


In [11]:
matrix_1 = np.random.randint(1, 10, (2, 2))
matrix_2 = np.random.randint(1, 10, (2, 2))
matrix_mult = np.dot(matrix_1, matrix_2)
print("Matrix Multiplication:\n", matrix_mult)

Matrix Multiplication:
 [[ 44  37]
 [153 144]]


In [12]:
arr_4x4 = np.arange(1, 17).reshape(4, 4)
diagonal_elements = arr_4x4[[0, 1, 2, 3], [0, 1, 2, 3]]
print("Diagonal Elements:", diagonal_elements)

Diagonal Elements: [ 1  6 11 16]
